server:
  port: 8086

spring:
  application:
    name:
      service-attribute

  datasource:
    url: jdbc:mysql://localhost:3306/fresh_selection?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: tjxt
    password: 123321
    virtual-host: /tjxt
    connection-timeout: 15000

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123321

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: QVJLeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=

seata:
  enabled: true
  application-id: ${spring.application.name}  # 应用唯一标识
  tx-service-group: default_tx_group  # 事务组名称（需与Seata Server配置一致）
  registry:
    type: nacos  # 注册中心类型（与微服务注册中心一致）
    nacos:
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      namespace: ""
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      data-id: seataServer.properties #Seata 再配置中心的名字
  service:
    vgroup-mapping:
      default_tx_group: default  # 事务组与Seata Server集群映射