server:
  port: 8082

spring:
  application:
    name:
      service-payment

  datasource:
    url: jdbc:mysql://localhost:3306/fresh_selection?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: tjxt
    password: 123321
    virtual-host: /tjxt
    connection-timeout: 15000

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123321

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: QVJLeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=

seata:
  enabled: true
  application-id: ${spring.application.name}  # 应用唯一标识
  tx-service-group: default_tx_group  # 事务组名称（需与Seata Server配置一致）
  registry:
    type: nacos  # 注册中心类型（与微服务注册中心一致）
    nacos:
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      namespace: ""
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      data-id: seataServer.properties #Seata 再配置中心的名字
  service:
    vgroup-mapping:
      default_tx_group: default  # 事务组与Seata Server集群映射

alipay:
  app_id: 9021000156668228
  private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDZvYULGCJeH/+BGhOA+W/XcAZTW0jT88QaSveep3zmbgtFM6mH+xY+yICp2pdEqzRFDVLqOC+b/4DwnnaRlNO9fSWyLXUgeVi4dBgOC1pZ+8Gep6/ZevPUeZvYP+rBBdDP9cCjbZQselJd97Ch8f3q/pLCHXX11jprYJdIdqDSL7xTmkHU3gmnTjukE6DS62yxMeQIxmvq9bOnlxRpZdiByQFjPBDwYjj8Alv760AfEdKdvaJf2YJ5uggBNQugR23f/uQxVs/1ajeHXeOfGoruUx36S+mNbIQs2udkpSTE7+jP/CQtj8BPRRCMC8RtIafwd+WRkaSzka95sAnpdwiPAgMBAAECggEBANZxyfNIPKjY+MoMhYLzp0vVv9UexVZB8TQ3+zIdIGzNmnn4TJJpHtqMm/MtHuf5eYw8eBnHZlRMSpAwcPQmUHeCJrsZ/A4UlOVtKTfDxKN0yJdZ7V3SswvjDTLomGqsMKBwF96dEF7RxgdX53VHoN1tBdr6KvAIohaY1cX/V5pIqXvN587dpOYQi6+4y1GomRkAIY8MxLmcc2E+CJYX7JQTtofaBj2OC0pOoc8Cko3uiUnMBbxi+WHdqZab5Dy+fmvJX/QJkFkXQuCtU8mj5+7ddZX1yttSI8K8hqF+AFWuoLwAgaLmXs+9wzkOcTBJ9SaTFR83oy5O9VZAnuNL96ECgYEA+ZRFGM9YfOPvTqY1GS/O+KotPu1D9BnkmYf3jNqO8jSQmCiWcLukCduyRWjQIZ5YhGd85c0vbp4gEzrD4hZPN4+0WjqT4NM8uZDazrTOOmw7lzRgZWAQ6ofES3+E8YiVXEtYRwVXmzfRqfo+FwKgZDz55uzhCJrUj8Y+BVwycDECgYEA31ePDYRGxwAala+iMQVb3Lu/CBFqD48Yi/ORk7fI5GfhUn4RDv8LBbq12maGKEsetYjkVFKxu7mXQNux9IMPvTlClnGpLAU4yrzGXu7cSD9XvefsxjrxMKO6DTrWXZafBSkG+zYoFzuxHoYWqbRoMzw4CyjXa/FipMx37UlJlL8CgYAP32YllcpC5xwpHFj0KR44oloOTnir5ZmsSgFsa9n7fWxUwQAQW16rYdWMpIXYHYHzqcE/vDTwDA5uKqaakmCnX/RQaLlO6yBJjPTdgJI9FPUVQLeAuwNYZxoM0ydZVR5qqEANBEH2FS64aLnaLMiWl2otTZNiQLaUDj+Th7GNgQKBgQDFMYHU5V24hpbyYshJj/mzwvDAJuAGLMn3h26ZhkORp0aCl1xoaTdKL7gwxSTenrTWg69V5E2Y+hxZ36AXy0AySkRIoMJFY7bpChP77doA0CygOA4OWCxsTaMP20s6BqsQ21CWrRJosQOJd8q6u9bkpd61u7G4VMBL0Vxx3ath8QKBgQCVgIONIGtZh4+K+mxxBvSthEogXWmNSKUpOico4QBbGHoAzldjSN6ygJ0jysIEb9bxfRhDRoTgBTbkwYtbRQ6h88Kegi/hixh2AeNL7Iqtek+di09CQbwPjvy4qCJpkyBbuYbHFkOU+Vx/g/mY7SiIrcI6MNPtDBSs+/HDI5zsRQ==
  # 支付宝公钥
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA05GMYkEl/YXcvhPC8a6083jADrAJbZ37Et8HI+ZRaHNftK2H5rejFWh2DeJbWtTD4J96CelWroRsC3n18DBRLsCldwYyBHHo0hgD1U/sd113PPGgfUh8phFc+dvjFnvUSQz+I9hDSwHtkAjyO4C54xHYRX2jkVlXhpGfRyMaKH3wBLbUD7Upaz9iGTta2hWde1TcwUxHZedM83aQTtooi+U0UkokxXpuxd6xb4b/2jC1EmJJ8Cw3rCVaVfhuWiqsI9f3/qEFg8yz/T8bkj8w1L33/6SrP1m3vV6AUjvrRMLVp+U9GH4b2Y0ZvAtAgsDKDtsNbEPG6NDIhwJQ50y4lwIDAQAB
  return_url: http://localhost:8080/api/alipay/return # 同步返回,需配置在支付宝的回调地址中

  notify_url: http://kce26d5f.natappfree.cc/api/alipay/notify # 异步通知,需配置在支付宝的异步通知地址中
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do # 支付宝网关