server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: service-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos注册中心
      discovery:
        group: DEFAULT_GROUP
        ip: 127.0.0.1
        namespace: public

#      config:
#        server-addr: 192.168.150.101:8848 # nacos注册中心
#        namespace: ""
#        file-extension: yaml
#        shared-configs: # 共享配置
#          - data-id: shared-spring.yaml # 共享spring配置
#            refresh: false
#          - data-id: shared-redis.yaml # 共享redis配置
#            refresh: false
#          - data-id: shared-logs.yaml # 共享日志配置
#            refresh: false