server:
  port: 8084

spring:
  application:
    name:
      service-user

  datasource:
    url: jdbc:mysql://localhost:3306/fresh_selection?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: tjxt
    password: 123321
    virtual-host: /tjxt
    connection-timeout: 15000

  data:
    redis:
       host: 127.0.0.1
       port: 6379
       database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
